#!/bin/bash
jupyter nbconvert --to notebook --execute 3-Logistische_Regression_Projekt-Loesung_Angepasst.ipynb --output 3-Logistische_Regression_Projekt-Loesung_Angepasst.ipynb 2>&1 | tee nbconvert.log
